theme = "kanagawa"
# theme = "material_palenight"

[keys.normal]
C-h = "jump_view_left"
C-l = "jump_view_right"
C-k = "jump_view_up"
C-j = "jump_view_down"
"ret" = "goto_word"
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
A-w = "move_next_sub_word_start"
A-e = "move_next_sub_word_end"
A-b = "move_prev_sub_word_start"

A-u = "scroll_up"
A-d = "scroll_down"
 

[keys.normal.space.space]
b = ":sh git blame -L %{cursor_line},%{cursor_line} %{buffer_name}"
r = ":reset-diff-change"
c = ["collapse_selection", "kill_to_line_end", "insert_mode"]
d = ["collapse_selection", "kill_to_line_end"]
s = "@mi(S,<ret><A-;>i<ret><esc>xs^\\s+<ret>df);i,<ret><esc>mi(_<gt>"

[keys.insert]
"C-["= "normal_mode"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
